name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s . -p 'test_*.py'

    - name: Deploy to server
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > key.pem
        chmod 600 key.pem
        scp -r -i key.pem . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/compute-vm-2-2-20-ssd-1735886767084/myproject1
        ssh -i key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'bash /home/compute-vm-2-2-20-ssd-1735886767084/myproject1/deploy.sh'
